Task #3
Siarhei-Karukhin/rss-aws-be pull request #1
Opened 2024-06-16 15:01 UTC by Siarhei-Karukhin

[Task](https://github.com/rolling-scopes-school/aws/blob/main/aws-developer/03_serverless_api/task.md)
Score: 100 / 100 (all criteria have been met)
Done: 16/06/2024, Deadline: 17/06/2024

Product Service API: https://5ua826jntg.execute-api.us-west-2.amazonaws.com/prod/products
[FE PR](https://github.com/Siarhei-Karukhin/rss-aws-dev-fe/pull/2/files)
[FE deploy](https://d2blyvzby6hxmo.cloudfront.net/)

2024-06-17 20:07 UTC, naXa777 requested changes

2024-06-17 20:07 UTC, naXa777 commented on openapi.yaml
> +                  $ref: '#/components/schemas/Product'
no matter how I try, your API does not return XML response. So this OpenAPI definition is misleading. Please remove
```suggestion
```

I tried different `accept` headers, but got the same JSON response, so I conclude that XML is not supported.
```
curl 'https://5ua826jntg.execute-api.us-west-2.amazonaws.com/prod/products' -H 'accept: application/xml'
curl 'https://5ua826jntg.execute-api.us-west-2.amazonaws.com/prod/products' -H 'accept: application/json'
```

2024-06-17 20:07 UTC, naXa777 commented on openapi.yaml
> +                $ref: '#/components/schemas/Product'
```suggestion
```

2024-06-17 20:07 UTC, naXa777 commented on openapi.yaml
> +          description: Not found
a tip: you can specify response body types for 404 - Not Found and 500 - Internal Error

example:
```suggestion
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
```

2024-06-17 20:07 UTC, naXa777 commented on openapi.yaml
> +    Product:
plus Define NotFound and InternalError schemas

```suggestion
    NotFound:
      type: string
      example: 'Not found'
    Product:
```

2024-06-17 20:07 UTC, naXa777 commented on openapi.yaml
> +        name: product
```suggestion
```

2024-06-17 20:07 UTC, naXa777 commented on openapi.yaml
> +      url: http://swagger.io
```suggestion
```

2024-06-17 20:07 UTC, naXa777 commented on openapi.yaml
> +    email: apiteam@swagger.io
here should be API support team contact
```suggestion
```

2024-06-17 20:07 UTC, naXa777 commented on openapi.yaml
> +  termsOfService: http://swagger.io/terms/
here should be your API ToS
```suggestion
```

2024-06-17 20:44 UTC, naXa777 requested changes

2024-06-17 20:44 UTC, naXa777 commented on test/rss-aws-developer-be.test.ts
> +    const response = await getProductsById({ pathParameters: { productId: '4' } });
this is a fragile test. when you add a product with id '4', this test will fail.

slightly better:
```suggestion
    const response = await getProductsById({ pathParameters: { productId: '-404' } });
```

2024-06-17 20:44 UTC, naXa777 commented on openapi.yaml
> +      description: Add a new product to the store
First, no need to write the same in `summary` and `description`. in `description` you can write more details, or skip it entirely.
Second, this is a misleading description.

2024-06-17 20:44 UTC, naXa777 commented on openapi.yaml
> +      operationId: addProduct
```suggestion
      operationId: getProductsList
```

2024-06-17 20:44 UTC, naXa777 commented on lambda/getProductsById.ts
> +      headers,
it would be better to set `"content-type": "application/json"` for the 200 OK response.

2024-06-17 20:44 UTC, naXa777 commented on lambda/getProductsList.ts
> +      headers,
the same. please use `"content-type": "application/json"` for the 200 OK response.

2024-06-17 20:44 UTC, naXa777 commented on lambda/mockData.ts
> +export const mockProducts = [
I recommend to define a type
```suggestion
export const mockProducts: Array<Product> = [
```

2024-06-17 20:54 UTC, naXa777 commented
please redeploy the front-end. it's still using old Get Products API URL
![image](https://github.com/Siarhei-Karukhin/rss-aws-dev-be/assets/3858548/004a500d-1276-42cd-9994-362456076ca6)

2024-06-18 00:20 UTC, russki007 approved these changes
👍. As per the previous comment, please update the S3 bucket with the latest changes.

-  [ ] Your own Frontend application is integrated with Product Service (/products API) and _**products from Product Service are represented on Frontend**._ AND POINT1 and POINT2 are done.

2024-06-28 11:18 UTC, closed without merging